# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
  # application.properties는 외부에 노출되면 안되므로 Actions가 빌드될때마다 해당 Repository의 Secret 설정을
    # 이용하여서 설정 파일을 생성해줌 (github에 commit 되는게 아님!)
    - run : touch ./outpolic/src/main/resources/application.properties
    - run : echo "${{ secrets.APP_PROPERTIES }}" > ./outpolic/src/main/resources/application.properties
    - run : cat ./outpolic/src/main/resources/application.properties
    
    - name: Build with Maven
      run: mvn clean package -DskipTests --file ./outpolic/pom.xml
      
    - name: Check built JAR file
      run: ls -lh ./outpolic/target/*.jar
      
    - name: jar file transfer server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.OCI_HOST }}
        username: ${{ secrets.OCI_USER }}
        key: ${{ secrets.OUTPOLICDEV }}
        source: "outpolic/target/*.jar"
        target: "${{ secrets.OCI_DEPLOY_PATH }}"
        strip_components: 2

    - name: Rename jar and restart service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.OCI_HOST }}
        username: ${{ secrets.OCI_USER }}
        key: ${{ secrets.OUTPOLICDEV }}
        script: |
          cd ${{ secrets.OCI_RELEASE }}
          sudo sh release.sh








      
